### ISSUE TITLE
Keyboard key changing

### ISSUE THREAD

**Issue by rubenwardy** [rubenwardy/NodeBoxEditor#38]
The user should be able to set custom keys for different actions.

One way is to create new key down and key up handling system, with generic key identifiers. Ie: key function, rather than key code. MenuMode::OnKeyDown() EditorMode::OnKeyDown()

The relevant key codes will be in an array in Editor class.

Although this will make it hard to add new keys in editor modes. But this shouldn't be too big a problem.

**Comment by MarkuBu** [comment]
I really need this because I don't use a standard keyboard layout, so WASD is a bit difficult for me. I use LIAE because I have a Neo2 layout and I prefer to use the ESDF keys
