### ISSUE TITLE
Window is very slow to move around

### ISSUE THREAD

**Issue by Calinou** [rubenwardy/NodeBoxEditor#57]
Window manager Xfwm 4.11, compositing enabled:
```
This is xfwm4 version 4.11.1 (revision 2b800f4) for Xfce 4.10
Compiled against GTK+-2.24.23, using GTK+-2.24.23.
```

When moving the window using mouse, the window will lag behind and move in a sluggish way.

**Comment by rubenwardy** [comment]
A few texture leaks have been fixed, can you check again?

**Comment by rubenwardy** [comment]
No reply for ages
