### ISSUE TITLE
Import nodes from lua

### ISSUE THREAD

**Issue by Amaz1** [rubenwardy/NodeBoxEditor#64]
Quite often, I fine myself with just the lua nodebox code, and no nodebox file. I've tried copying the code from lua into a .nbe file (with the correct format, as far as I can see) but nodeboxeditor just hangs and needs to be killed. So, being able to import nodes straight from lua would be a very nice feature!

**Comment by rubenwardy** [comment]
I don't want to have to set up a whole Lua sandbox, that's excessively painful. I'd probably just use pattern matching. The .nbe file is a binary file, so there will be problems when saving it in a text editor.
