### ISSUE TITLE
Handles going into other viewports when resizing

### ISSUE THREAD

**Issue by rubenwardy** [rubenwardy/NodeBoxEditor#65]
![resizing](https://cloud.githubusercontent.com/assets/2122943/7554826/80f262e0-f72f-11e4-9070-4025baaf7fb7.png)

**Comment by rubenwardy** [comment]
Zooming has no been added, should the viewport automatically zoom out, or should we just hide the handle if it's out of bounds?

**Comment by VanessaE** [comment]
Just hide the handle after the user lets go of it, put some marker at the viewport edge that suggests it's out of bounds (like how some editors put a $ at the right if the line is too long), and let the user zoom out as needed.

**Comment by rubenwardy** [comment]
4af82d6b711f2a8f8c2b034dc2661c50a9adddb8
