### ISSUE TITLE
Rotating the Preview viewport with WASD keys is very slow?

### ISSUE THREAD

**Issue by Flairieve** [rubenwardy/NodeBoxEditor#82]
NodeBoxEditor works completely for me, but when using the WASD keys, the movement in the Preview port is very slow. It takes me forever to rotate the screen? I'm running on Windows 10. I have no clue to why this is happening? Thanks for reading this comment!

**Comment by LoneWolfHT** [comment]
![nbe](https://user-images.githubusercontent.com/28972859/38126902-591659c6-33a8-11e8-8b55-1412f5ef41bf.gif)
It works slower for me when I have more programs open

**Comment by rubenwardy** [comment]
I probably forgot to multiple the rotate delta by the dtime, meaning the speed depends on the frame rate

**Comment by SmallJoker** [comment]
I already checked for that ^. But the values are already multiplied by dtime.
https://github.com/rubenwardy/NodeBoxEditor/blob/2d5f87f2874e1e1d5bf6f575385cc49ebbe671ee/src/Editor.cpp#L192-L202
