### ISSUE TITLE
libpng12-dev is no longer used for Linux Install

### ISSUE THREAD

**Issue by TechRancher** [rubenwardy/NodeBoxEditor#86]
I tried to compile NodeBoxEditor with Ubuntu 18.04 and used your "sudo apt-get install build-essential libirrlicht-dev cmake libpng12-dev libbz2-dev libjpeg8-dev libgl1-mesa-dev"
but came up with libpng12-dev error. 
I did some searching and found you can use libpng-dev instead.  
It should be updated in your doc/developer.md under Linux Install Dependencies

**Comment by SmallJoker** [comment]
Indeed. CMake also finds libpng-dev here on 18.04.3
`-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.2.54")`

**Comment by Calinou** [comment]
[`libpng-dev` is available on Ubuntu 16.04 and later](https://packages.ubuntu.com/search?keywords=libpng-dev), so it should be fine to recommend it by default.
