### ISSUE TITLE
Library list incomplete in developers.md

### ISSUE THREAD

**Issue by wcleg4** [rubenwardy/NodeBoxEditor#88]
With NodeBoxEditor-0.9.2 the docs do not specify the need for libxxf86vm-dev which at least from what I can tell does not come with ubuntu 18.04 by default.
After running
`# apt install libxxf86vm-dev`
and
`# apt install libxxf86vm1-dbg`
the problem resolved.

**Comment by Calinou** [comment]
Installing the debug symbols shouldn't be required, so only `libxxf86vm-dev` is actually needed here.
